apiVersion: v1
kind: Service
metadata:
  name: android-studio-service
  namespace: android-appium-namespace
spec:
  selector:
    app: android-studio
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
  - protocol: TCP
    port: 5901
    targetPort: 5901