apiVersion: v1
kind: Service
metadata:
  name: appium-service
  namespace: android-appium-namespace
spec:
  selector:
    app: appium
  ports:
  - protocol: TCP
    port: 4723
    targetPort: 4723
  - protocol: TCP
    port: 5901
    targetPort: 5901